language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
script:
  - npm test
  - node lib/run.js --mapping test-data/test-mapping.json --inCsv test-data/test-small.csv
branches:
  only:
    - master